### ISSUE TITLE
Errors in Logcat for the added profile views

### ISSUE THREAD

**Issue by RobbieTechie** [ElJaviLuki/GrindrPlus#38]
I'm getting errors for the added profile views, even though they are showing up and working,   there are errors there in logcat.  I downloaded and compiled the code and commented out that section and the errors are gone.  This started happening a few versions of Grindr ago.

My concern is the errors being sent to Grindr as I had one of their employees message me in the past on XDA letting me know that an old patch that had errors for people jwas being sent to them, I think through crashlytics.

I've tested this one a couple devices, one with EdXposed and another with LSPosed, both get the errors about the params being null even though the profileID shows up and the mod works fine.  EdXposed was on Android 9 but I wasn't sure if that is the issue there.  Below are parts of the log copied from logcat, with date and time removed...

Thank you for the awesome mod and all the hard work you've put into it!!  It's appreciated.

[**date/time redacted** E/LSPosed-Bridge]
java.lang.NullPointerException: param.args[0] must not be null
	at com.eljaviluki.grindrplus.Hooks$addExtraProfileFields$1.afterHookedMethod(Hooks.kt:121)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.h(Unknown Source:14)
	at com.grindrapp.android.ui.profileV2.ProfileFieldsView$a.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:4)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:18)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7617)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
	
[**date/time redacted** E/LSPosed-Bridge]
java.lang.NullPointerException: param.args[0] must not be null
	at com.eljaviluki.grindrplus.Hooks$addExtraProfileFields$1.afterHookedMethod(Hooks.kt:121)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.h(Unknown Source:14)
	at com.grindrapp.android.ui.profileV2.ProfileFieldsView$a.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:4)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:18)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7617)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

**Comment by ElJaviLuki** [comment]
Thanks for opening this issue! I've gone ahead and fixed the problem in commit #ad5cd86. Let me know if you have any questions or if there are any other issues you'd like to look into.
